//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveDetail
    {
        public int Id { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string PersonName { get; set; }
        public Nullable<bool> IsStudent { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string LeaveReason { get; set; }
        public Nullable<int> LeaveStatus { get; set; }
    }
}
